@url = http://localhost:3000

###
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "rama123",
    "password": "Rama123."
}

###
@token = {{login.response.body.token}}

### Obtener la lista de profesores y sus materias asignadas
GET {{url}}/teachers_subjects
Authorization: Bearer {{token}}

### Asignar una materia a un profesor
POST {{url}}/teachers_subjects
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "teacher_id": 1,
  "subject_id": 1
}
