@url=http://localhost:3000

###LOGUEARME
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "ana123", 
    "password": "Ana123456@"

}

###
@token = {{login.response.body.token}}  



