@url = http://localhost:3000

###
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "juan123",
    "password": "Juan123@"
}

###
@token = {{login.response.body.token}}  


###
GET {{url}}/students
Authorization: Bearer {{token}}


###
GET {{url}}/students/1
Authorization: Bearer {{token}}


###
POST {{url}}/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Celeste",
  "last_name": "Fernández",
  "dni": "1080249", 
  "school": "CPUGSM", 
  "birth_date": "2004-01-13",
  "enrolled": true,
  "level": "universitario", 
  "grade": 7
}

###
PUT {{url}}/students/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Julia",
  "last_name": "Fernández",
  "dni": "48681322", 
  "school": "CPUGSM", 
  "birth_date": "2004-01-13",
  "enrolled": true,
  "level": "universitario", 
  "grade": 2
}

###
DELETE {{url}}/students/12
Authorization: Bearer {{token}}