@url=http://localhost:3000

###
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "rama123",
    "password": "Rama123."
}

###
@token = {{login.response.body.token}}

###
GET {{url}}/student_plans
Authorization: Bearer {{token}}

###
GET {{url}}/student_plans/1
Authorization: Bearer {{token}}

### NO SÉ QUÉ ES
GET {{url}}/students/1/payments
Authorization: Bearer {{token}}

###
POST {{url}}/student_plans
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 1,
    "plan_id": 2,
    "paid_amount": 15000,
    "start_date": "2023-01-01"
}

###
PUT {{url}}/student_plans/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "student_id": 1,
    "plan_id": 1,
    "paid_amount": 15000,
    "start_date": "2023-01-01"
}

###
DELETE {{url}}/student_plans/1
Authorization: Bearer {{token}}