@url = http://localhost:3000

###
GET {{url}}/subjects


###
GET {{url}}/subjects/1

###
POST {{url}}/subjects
Content-Type: application/json

{
    "name": "lengua"
}

###
PUT {{url}}/subjects/1
Content-Type: application/json

{
    "name": "matematicas"
}

###
DELETE {{url}}/subjects/1