@url = http://localhost:3000


###
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "rama123",
    "password": "Rama123."
}

###
@token = {{login.response.body.token}}  

###
GET {{url}}/subjects
Authorization: Bearer {{token}}

###
GET {{url}}/subjects/4
Authorization: Bearer {{token}}

###
POST {{url}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "gimnasia artistica"
}

###
PUT {{url}}/subjects/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "canto"
}

###
DELETE {{url}}/subjects/2
Authorization: Bearer {{token}}