@url=http://localhost:3000

### Iniciar sesión para obtener el token
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "juan123",
    "password": "Juan123@"
}

### Guardar el token en una variable
@token = {{login.response.body.token}}

### Obtener todos los docentes (Requiere autenticación)
GET {{url}}/teachers
Authorization: Bearer {{token}}

### Obtener un docente por ID (Requiere autenticación)
GET {{url}}/teachers/1
Authorization: Bearer {{token}}

### Crear un nuevo docente (Requiere autenticación)
POST {{url}}/teachers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "ramiro",
    "last_name": "pioli",
    "dni": "43212488",
    "phone": "3804987654",
    "salary": 60000.00
}

### Actualizar un docente (Requiere autenticación)
PUT {{url}}/teachers/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "celeste",
    "last_name": "antenao",
    "dni": "44323565",
    "phone": "3804432213",
    "salary": 65000.50
}

### Eliminar un docente (Requiere autenticación)
DELETE {{url}}/teachers/1
Authorization: Bearer {{token}}
