@url = http://localhost:3000

### Obtener todos los tutores
GET {{url}}/tutores


### Obtener un tutor por ID
GET {{url}}/tutores/1


### Crear tutor
POST {{url}}/tutores
Content-Type: application/json

{
    "nombre": "ramiro",
    "apellido": "pioli",
    "telefono": "3804312768",
    "dni": "43212488"
}

### Actualizar tutor
PUT {{url}}/tutores/1
Content-Type: application/json

{
    "nombre": "exequeil",
    "apellido": "mendoza",
    "telefono": "3804564322",
    "dni": "34452234"
}

### Eliminar tutor
DELETE {{url}}/tutores/1
