@url=http://localhost:3000

### Iniciar sesión para obtener el token
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "rama123",
    "password": "Rama123."
}

### Guardar el token en una variable
@token = {{login.response.body.token}}

### Obtener tutores
GET {{url}}/tutors
Authorization: Bearer {{token}}

### Obtener un tutor por ID (Requiere autenticación)
GET {{url}}/tutors/1
Authorization: Bearer {{token}}

### Crear un nuevo tutor (Requiere autenticación)
POST {{url}}/tutors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "Ramiro",
    "last_name": "Pioli",
    "phone": "3804312768",
    "dni": "43212488"
}

### Actualizar un tutor (Requiere autenticación)
PUT {{url}}/tutors/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "Exequel",
    "last_name": "mendoza",
    "phone": "3804546632",
    "dni": "35432568"
}

### Eliminar un tutor (Requiere autenticación)
DELETE {{url}}/tutors/1
Authorization: Bearer {{token}}
