@url = http://localhost:3000

### Obtener todos los tutors
GET {{url}}/tutors


### Obtener un tutor por ID
GET {{url}}/tutors/1


### Crear tutor
POST {{url}}/tutors
Content-Type: application/json

{
    "first_name": "ramiro",
    "last_name": "pioli",
    "phone": "3804312768",
    "dni": "43212488"
}

### Actualizar tutor
PUT {{url}}/tutors/1
Content-Type: application/json

{
    "first_name": "exequeil",
    "last_name": "mendoza",
    "phone": "3804564322",
    "dni": "34452234"
}

### Eliminar tutor
DELETE {{url}}/tutors/1
